   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: spring-demo
   spec:
     selector:
       matchLabels:
         app: spring-demo
     template:
       metadata:
         labels:
           app: spring-demo
       spec:
         containers:
         - name: spring-demo
           image: image-registry.openshift-image-registry.svc:5000/sunila123-dev/spring-openshift:latest
    
---

apiVersion: v1
kind: Service
metadata:
  name: spring-demo
spec:
   
  selector:
    app: spring-demo
  ports:
  - port: 8080
    targetPort: 8080
    



           
   
   